/**
 * Local Agent Store
 *
 * Simple JSON-based storage for agent tasks and recommendations.
 * Used by solo projects (SidelineIQ, Dosie) that don't have a database.
 *
 * Usage:
 *   import { AgentStore } from './agent-store'
 *   const store = new AgentStore()
 *   await store.createTask({ ... })
 */

import { readFile, writeFile, mkdir } from "fs/promises"
import { existsSync } from "fs"
import { join, dirname } from "path"
import { randomUUID } from "crypto"

// Types
export type AgentType = "CONTENT" | "ANALYTICS" | "RESEARCH" | "BRIEFING" | "DEVELOPMENT"
export type TaskStatus = "PENDING" | "RUNNING" | "COMPLETED" | "FAILED"
export type Priority = "LOW" | "MEDIUM" | "HIGH" | "URGENT"
export type HumanDecision = "APPROVED" | "REJECTED" | "MODIFIED"

export interface AgentTask {
  id: string
  agentType: AgentType
  status: TaskStatus
  prompt: string
  result?: string
  createdAt: string
  completedAt?: string
  project: string
}

export interface AgentRecommendation {
  id: string
  agentType: AgentType
  taskId?: string
  title: string
  recommendation: Record<string, unknown>
  reasoning: string
  priority: Priority
  humanDecision?: HumanDecision
  humanReasoning?: string
  appliedAt?: string
  createdAt: string
  project: string
}

export interface AgentAlert {
  id: string
  agentType: AgentType
  title: string
  summary: string
  details?: Record<string, unknown>
  priority: Priority
  acknowledgedAt?: string
  createdAt: string
  project: string
}

export interface AgentStoreData {
  tasks: AgentTask[]
  recommendations: AgentRecommendation[]
  alerts: AgentAlert[]
  lastUpdated: string | null
}

const DEFAULT_DATA: AgentStoreData = {
  tasks: [],
  recommendations: [],
  alerts: [],
  lastUpdated: null,
}

export class AgentStore {
  private dataPath: string
  private data: AgentStoreData | null = null

  constructor(dataPath?: string) {
    this.dataPath = dataPath || join(dirname(new URL(import.meta.url).pathname), "../data/tasks.json")
  }

  private async ensureDataFile(): Promise<void> {
    if (!existsSync(this.dataPath)) {
      const dir = dirname(this.dataPath)
      if (!existsSync(dir)) {
        await mkdir(dir, { recursive: true })
      }
      await writeFile(this.dataPath, JSON.stringify(DEFAULT_DATA, null, 2))
    }
  }

  async load(): Promise<AgentStoreData> {
    await this.ensureDataFile()
    const content = await readFile(this.dataPath, "utf-8")
    this.data = JSON.parse(content)
    return this.data!
  }

  async save(): Promise<void> {
    if (!this.data) return
    this.data.lastUpdated = new Date().toISOString()
    // Write JSON file (for programmatic access)
    await writeFile(this.dataPath, JSON.stringify(this.data, null, 2))
    // Write JS file (for browser loading via file:// protocol)
    const jsPath = this.dataPath.replace("tasks.json", "data.js")
    const jsContent = `// Auto-generated by agent scripts - do not edit\nconst AGENT_DATA = ${JSON.stringify(this.data, null, 2)};\n`
    await writeFile(jsPath, jsContent)
  }

  // Task methods
  async createTask(params: {
    agentType: AgentType
    prompt: string
    project: string
  }): Promise<AgentTask> {
    await this.load()
    const task: AgentTask = {
      id: randomUUID(),
      agentType: params.agentType,
      status: "RUNNING",
      prompt: params.prompt,
      createdAt: new Date().toISOString(),
      project: params.project,
    }
    this.data!.tasks.push(task)
    await this.save()
    return task
  }

  async completeTask(taskId: string, result: string): Promise<AgentTask | null> {
    await this.load()
    const task = this.data!.tasks.find((t) => t.id === taskId)
    if (!task) return null
    task.status = "COMPLETED"
    task.result = result
    task.completedAt = new Date().toISOString()
    await this.save()
    return task
  }

  async failTask(taskId: string, error: string): Promise<AgentTask | null> {
    await this.load()
    const task = this.data!.tasks.find((t) => t.id === taskId)
    if (!task) return null
    task.status = "FAILED"
    task.result = JSON.stringify({ error })
    task.completedAt = new Date().toISOString()
    await this.save()
    return task
  }

  // Recommendation methods
  async createRecommendation(params: {
    agentType: AgentType
    taskId?: string
    title: string
    recommendation: Record<string, unknown>
    reasoning: string
    priority: Priority
    project: string
  }): Promise<AgentRecommendation> {
    await this.load()
    const rec: AgentRecommendation = {
      id: randomUUID(),
      agentType: params.agentType,
      taskId: params.taskId,
      title: params.title,
      recommendation: params.recommendation,
      reasoning: params.reasoning,
      priority: params.priority,
      createdAt: new Date().toISOString(),
      project: params.project,
    }
    this.data!.recommendations.push(rec)
    await this.save()
    return rec
  }

  async decideRecommendation(
    recId: string,
    decision: HumanDecision,
    reasoning?: string
  ): Promise<AgentRecommendation | null> {
    await this.load()
    const rec = this.data!.recommendations.find((r) => r.id === recId)
    if (!rec) return null
    rec.humanDecision = decision
    rec.humanReasoning = reasoning
    if (decision === "APPROVED") {
      rec.appliedAt = new Date().toISOString()
    }
    await this.save()
    return rec
  }

  // Alert methods
  async createAlert(params: {
    agentType: AgentType
    title: string
    summary: string
    details?: Record<string, unknown>
    priority: Priority
    project: string
  }): Promise<AgentAlert> {
    await this.load()
    const alert: AgentAlert = {
      id: randomUUID(),
      agentType: params.agentType,
      title: params.title,
      summary: params.summary,
      details: params.details,
      priority: params.priority,
      createdAt: new Date().toISOString(),
      project: params.project,
    }
    this.data!.alerts.push(alert)
    await this.save()
    return alert
  }

  async acknowledgeAlert(alertId: string): Promise<AgentAlert | null> {
    await this.load()
    const alert = this.data!.alerts.find((a) => a.id === alertId)
    if (!alert) return null
    alert.acknowledgedAt = new Date().toISOString()
    await this.save()
    return alert
  }

  // Query methods
  async getPendingRecommendations(project?: string): Promise<AgentRecommendation[]> {
    await this.load()
    return this.data!.recommendations.filter(
      (r) =>
        r.humanDecision === undefined &&
        (project === undefined || r.project === project)
    )
  }

  async getActiveAlerts(project?: string): Promise<AgentAlert[]> {
    await this.load()
    return this.data!.alerts.filter(
      (a) =>
        a.acknowledgedAt === undefined &&
        (project === undefined || a.project === project)
    )
  }

  async getRecentTasks(limit = 10, project?: string): Promise<AgentTask[]> {
    await this.load()
    const filtered = project
      ? this.data!.tasks.filter((t) => t.project === project)
      : this.data!.tasks
    return filtered
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, limit)
  }

  // Get all data for dashboard
  async getDashboardData(project?: string): Promise<{
    pendingRecommendations: AgentRecommendation[]
    activeAlerts: AgentAlert[]
    recentTasks: AgentTask[]
    stats: {
      totalTasks: number
      pendingApprovals: number
      activeAlerts: number
      tasksToday: number
    }
  }> {
    await this.load()

    const filterByProject = <T extends { project: string }>(items: T[]) =>
      project ? items.filter((i) => i.project === project) : items

    const tasks = filterByProject(this.data!.tasks)
    const recommendations = filterByProject(this.data!.recommendations)
    const alerts = filterByProject(this.data!.alerts)

    const today = new Date().toDateString()
    const tasksToday = tasks.filter(
      (t) => new Date(t.createdAt).toDateString() === today
    ).length

    return {
      pendingRecommendations: recommendations.filter((r) => !r.humanDecision),
      activeAlerts: alerts.filter((a) => !a.acknowledgedAt),
      recentTasks: tasks
        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
        .slice(0, 10),
      stats: {
        totalTasks: tasks.length,
        pendingApprovals: recommendations.filter((r) => !r.humanDecision).length,
        activeAlerts: alerts.filter((a) => !a.acknowledgedAt).length,
        tasksToday,
      },
    }
  }

  // Cleanup old data (keep last 30 days)
  async cleanup(daysToKeep = 30): Promise<{ removed: number }> {
    await this.load()
    const cutoff = new Date()
    cutoff.setDate(cutoff.getDate() - daysToKeep)

    const originalCount =
      this.data!.tasks.length + this.data!.recommendations.length + this.data!.alerts.length

    this.data!.tasks = this.data!.tasks.filter(
      (t) => new Date(t.createdAt) > cutoff
    )
    this.data!.recommendations = this.data!.recommendations.filter(
      (r) => new Date(r.createdAt) > cutoff
    )
    this.data!.alerts = this.data!.alerts.filter(
      (a) => new Date(a.createdAt) > cutoff
    )

    await this.save()

    const newCount =
      this.data!.tasks.length + this.data!.recommendations.length + this.data!.alerts.length

    return { removed: originalCount - newCount }
  }
}

// Export singleton for convenience
export const agentStore = new AgentStore()
