/**
 * Mark a recommendation as approved or rejected
 *
 * Usage: npx tsx scripts/decide.ts <rec-id-suffix> <APPROVED|REJECTED>
 *
 * The rec-id-suffix is the last 8 characters of the recommendation ID
 */

import { readFile, writeFile } from "fs/promises"
import { join, dirname } from "path"

const DATA_PATH = join(dirname(new URL(import.meta.url).pathname), "../data/tasks.json")

interface AgentStoreData {
  tasks: any[]
  recommendations: any[]
  alerts: any[]
  lastUpdated: string | null
}

async function main() {
  const [,, idSuffix, decision] = process.argv

  if (!idSuffix || !decision) {
    console.error("Usage: npx tsx scripts/decide.ts <rec-id-suffix> <APPROVED|REJECTED>")
    console.error("Example: npx tsx scripts/decide.ts abc12345 APPROVED")
    process.exit(1)
  }

  if (!["APPROVED", "REJECTED"].includes(decision)) {
    console.error("Decision must be APPROVED or REJECTED")
    process.exit(1)
  }

  const content = await readFile(DATA_PATH, "utf-8")
  const data: AgentStoreData = JSON.parse(content)

  // Find recommendation by ID suffix
  const rec = data.recommendations.find(r => r.id.endsWith(idSuffix))

  if (!rec) {
    console.error(`No recommendation found ending with: ${idSuffix}`)
    console.error("\nAvailable recommendations:")
    data.recommendations.forEach(r => {
      if (!r.humanDecision) {
        console.error(`  ${r.id.slice(-8)} - ${r.title} [${r.project}]`)
      }
    })
    process.exit(1)
  }

  if (rec.humanDecision) {
    console.log(`Already decided: ${rec.humanDecision}`)
    process.exit(0)
  }

  // Update the recommendation
  rec.humanDecision = decision
  rec.decidedAt = new Date().toISOString()

  // Save
  data.lastUpdated = new Date().toISOString()
  await writeFile(DATA_PATH, JSON.stringify(data, null, 2))

  // Also write JS file for browser
  const jsPath = DATA_PATH.replace("tasks.json", "data.js")
  const jsContent = `// Auto-generated by agent scripts - do not edit\nconst AGENT_DATA = ${JSON.stringify(data, null, 2)};\n`
  await writeFile(jsPath, jsContent)

  console.log(`✅ ${decision}: ${rec.title}`)
  console.log(`   Project: ${rec.project}`)

  if (decision === "APPROVED") {
    console.log(`\n📋 To execute this recommendation, run:`)
    console.log(`   /execute-approved`)
  }
}

main().catch(console.error)
