/**
 * Regenerate data.js from tasks.json
 * Run after manually editing tasks.json
 */

import { readFile, writeFile } from "fs/promises"
import { join, dirname } from "path"

const DATA_PATH = join(dirname(new URL(import.meta.url).pathname), "../data/tasks.json")

async function main() {
  const content = await readFile(DATA_PATH, "utf-8")
  const data = JSON.parse(content)

  const jsPath = DATA_PATH.replace("tasks.json", "data.js")
  const jsContent = `// Auto-generated by agent scripts - do not edit\nconst AGENT_DATA = ${JSON.stringify(data, null, 2)};\n`
  await writeFile(jsPath, jsContent)

  console.log("✅ Regenerated data.js")
}

main().catch(console.error)
