/**
 * Cost computation helper for managed-agents sessions.
 *
 * Provides a single pure function that converts token counts into a USD
 * estimate using a hard-coded rate table. Called from:
 *
 *   - `session-stream.ts::waitForIdle` — populates SessionUsage.total_cost_usd
 *     once the session returns an `end_turn` idle.
 *   - `supabase-writer.ts::writeAgentRun` — currently reads the value that
 *     session-stream already computed, but imports this module as a safety
 *     net in case a caller hand-crafts a SessionUsage in tests.
 *
 * Rate table is hard-coded from Anthropic's public pricing as of April 2026
 * and should be updated when models change. Values are in USD per million
 * tokens (1M = 1,000,000). The computeCostUsd function returns a plain
 * number in USD.
 *
 * The advisor tool pairs an executor model with an advisor model; both
 * are charged at their respective per-million rates. An executor-only
 * call (advisor tokens all zero) simply skips the advisor math.
 *
 * ADVISOR STATUS ON MANAGED AGENTS (2026-04 cutover):
 * Advisor tool (advisor_20260301) is NOT yet supported on the Managed
 * Agents SDK — only on the Messages API. See the repo skill
 * `anthropic-advisor-tool-managed-agents-mismatch` and the BETAS lists
 * in reviewer.ts / worker.ts (neither includes an advisor beta).
 * session-stream.ts::waitForIdle documents this explicitly and aggregates
 * every `span.model_request_end` token count into `executor_*`, leaving
 * `advisor_*` at 0.
 *
 * Net effect on the math here: computeCostUsd's advisor branch is
 * exercised by tests (see __tests__/cost.test.ts) but contributes $0.00
 * to every real session today. We keep the branch in place rather than
 * stripping it because (a) the math is correct at zero (no change needed
 * when the SDK adds advisor support), and (b) the Messages API path in
 * other tools in this repo DOES use advisor and shares this helper.
 * Re-evaluate this decision if the advisor code paths remain unused when
 * Managed Agents reaches GA. — CC 27544d33.
 */

// ---------------------------------------------------------------------------
// Rate table — keep in sync with shared/models.md
// ---------------------------------------------------------------------------

export type ModelName =
  | 'claude-opus-4-6'
  | 'claude-sonnet-4-6'
  | 'claude-haiku-4-5';

interface ModelRate {
  /** USD per 1,000,000 input tokens. */
  input: number;
  /** USD per 1,000,000 output tokens. */
  output: number;
}

export const MODEL_RATES_PER_MILLION: Record<ModelName, ModelRate> = {
  'claude-opus-4-6': { input: 5, output: 25 },
  'claude-sonnet-4-6': { input: 3, output: 15 },
  'claude-haiku-4-5': { input: 1, output: 5 },
};

// Advisor runs on Opus 4.6 across all three agent roles in the managed
// pipeline. If a future agent pairs a different advisor model, the
// computeCostUsd signature takes an `advisor_model` override.
const DEFAULT_ADVISOR_MODEL: ModelName = 'claude-opus-4-6';

// ---------------------------------------------------------------------------
// computeCostUsd
// ---------------------------------------------------------------------------

export interface CostInput {
  /** Which model ran the executor turns. */
  executor_model: ModelName;
  /** Total input tokens consumed by the executor across all turns. */
  executor_input: number;
  /** Total output tokens generated by the executor across all turns. */
  executor_output: number;
  /** Total input tokens consumed by the advisor across all sub-inferences.
   *  Pass 0 when the session did not use advisor. */
  advisor_input: number;
  /** Total output tokens generated by the advisor across all sub-inferences.
   *  Pass 0 when the session did not use advisor. */
  advisor_output: number;
  /** Optional override — defaults to claude-opus-4-6. */
  advisor_model?: ModelName;
}

/**
 * Returns a USD cost estimate for the given token counts. The result is
 * a plain number (not a Decimal) — downstream callers should round to 4
 * decimal places before displaying or persisting. Returns 0 for the
 * all-zeros case without dividing.
 */
export function computeCostUsd(input: CostInput): number {
  const execRate = MODEL_RATES_PER_MILLION[input.executor_model];
  if (!execRate) {
    throw new Error(
      `Unknown executor model in cost computation: ${input.executor_model}`,
    );
  }
  const advisorModel = input.advisor_model ?? DEFAULT_ADVISOR_MODEL;
  const advisorRate = MODEL_RATES_PER_MILLION[advisorModel];
  if (!advisorRate) {
    throw new Error(
      `Unknown advisor model in cost computation: ${advisorModel}`,
    );
  }

  const executorCost =
    (input.executor_input * execRate.input) / 1_000_000 +
    (input.executor_output * execRate.output) / 1_000_000;

  const advisorCost =
    (input.advisor_input * advisorRate.input) / 1_000_000 +
    (input.advisor_output * advisorRate.output) / 1_000_000;

  return executorCost + advisorCost;
}
